/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBase64Decoder {
    }
    interface AppBase64Encoder {
    }
    interface AppHome {
    }
    interface AppHtmlDecoder {
    }
    interface AppHtmlEncoder {
    }
    interface AppInfo {
        "description": string;
        "title": string;
    }
    interface AppInput {
        "label": string;
        "side": boolean;
    }
    interface AppJsonParser {
    }
    interface AppJwt {
    }
    interface AppMarkdown {
    }
    interface AppOutput {
        "highlight": any;
        "html": boolean;
        "label": string;
        "side": boolean;
        "value": string;
    }
    interface AppQueryStringToJson {
    }
    interface AppRoot {
    }
    interface AppUrlDecoder {
    }
    interface AppUrlEncoder {
    }
}
declare global {
    interface HTMLAppBase64DecoderElement extends Components.AppBase64Decoder, HTMLStencilElement {
    }
    var HTMLAppBase64DecoderElement: {
        prototype: HTMLAppBase64DecoderElement;
        new (): HTMLAppBase64DecoderElement;
    };
    interface HTMLAppBase64EncoderElement extends Components.AppBase64Encoder, HTMLStencilElement {
    }
    var HTMLAppBase64EncoderElement: {
        prototype: HTMLAppBase64EncoderElement;
        new (): HTMLAppBase64EncoderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppHtmlDecoderElement extends Components.AppHtmlDecoder, HTMLStencilElement {
    }
    var HTMLAppHtmlDecoderElement: {
        prototype: HTMLAppHtmlDecoderElement;
        new (): HTMLAppHtmlDecoderElement;
    };
    interface HTMLAppHtmlEncoderElement extends Components.AppHtmlEncoder, HTMLStencilElement {
    }
    var HTMLAppHtmlEncoderElement: {
        prototype: HTMLAppHtmlEncoderElement;
        new (): HTMLAppHtmlEncoderElement;
    };
    interface HTMLAppInfoElement extends Components.AppInfo, HTMLStencilElement {
    }
    var HTMLAppInfoElement: {
        prototype: HTMLAppInfoElement;
        new (): HTMLAppInfoElement;
    };
    interface HTMLAppInputElement extends Components.AppInput, HTMLStencilElement {
    }
    var HTMLAppInputElement: {
        prototype: HTMLAppInputElement;
        new (): HTMLAppInputElement;
    };
    interface HTMLAppJsonParserElement extends Components.AppJsonParser, HTMLStencilElement {
    }
    var HTMLAppJsonParserElement: {
        prototype: HTMLAppJsonParserElement;
        new (): HTMLAppJsonParserElement;
    };
    interface HTMLAppJwtElement extends Components.AppJwt, HTMLStencilElement {
    }
    var HTMLAppJwtElement: {
        prototype: HTMLAppJwtElement;
        new (): HTMLAppJwtElement;
    };
    interface HTMLAppMarkdownElement extends Components.AppMarkdown, HTMLStencilElement {
    }
    var HTMLAppMarkdownElement: {
        prototype: HTMLAppMarkdownElement;
        new (): HTMLAppMarkdownElement;
    };
    interface HTMLAppOutputElement extends Components.AppOutput, HTMLStencilElement {
    }
    var HTMLAppOutputElement: {
        prototype: HTMLAppOutputElement;
        new (): HTMLAppOutputElement;
    };
    interface HTMLAppQueryStringToJsonElement extends Components.AppQueryStringToJson, HTMLStencilElement {
    }
    var HTMLAppQueryStringToJsonElement: {
        prototype: HTMLAppQueryStringToJsonElement;
        new (): HTMLAppQueryStringToJsonElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppUrlDecoderElement extends Components.AppUrlDecoder, HTMLStencilElement {
    }
    var HTMLAppUrlDecoderElement: {
        prototype: HTMLAppUrlDecoderElement;
        new (): HTMLAppUrlDecoderElement;
    };
    interface HTMLAppUrlEncoderElement extends Components.AppUrlEncoder, HTMLStencilElement {
    }
    var HTMLAppUrlEncoderElement: {
        prototype: HTMLAppUrlEncoderElement;
        new (): HTMLAppUrlEncoderElement;
    };
    interface HTMLElementTagNameMap {
        "app-base64-decoder": HTMLAppBase64DecoderElement;
        "app-base64-encoder": HTMLAppBase64EncoderElement;
        "app-home": HTMLAppHomeElement;
        "app-html-decoder": HTMLAppHtmlDecoderElement;
        "app-html-encoder": HTMLAppHtmlEncoderElement;
        "app-info": HTMLAppInfoElement;
        "app-input": HTMLAppInputElement;
        "app-json-parser": HTMLAppJsonParserElement;
        "app-jwt": HTMLAppJwtElement;
        "app-markdown": HTMLAppMarkdownElement;
        "app-output": HTMLAppOutputElement;
        "app-query-string-to-json": HTMLAppQueryStringToJsonElement;
        "app-root": HTMLAppRootElement;
        "app-url-decoder": HTMLAppUrlDecoderElement;
        "app-url-encoder": HTMLAppUrlEncoderElement;
    }
}
declare namespace LocalJSX {
    interface AppBase64Decoder {
    }
    interface AppBase64Encoder {
    }
    interface AppHome {
    }
    interface AppHtmlDecoder {
    }
    interface AppHtmlEncoder {
    }
    interface AppInfo {
        "description"?: string;
        "title"?: string;
    }
    interface AppInput {
        "label"?: string;
        "onTransform"?: (event: CustomEvent<any>) => void;
        "side"?: boolean;
    }
    interface AppJsonParser {
    }
    interface AppJwt {
    }
    interface AppMarkdown {
    }
    interface AppOutput {
        "highlight"?: any;
        "html"?: boolean;
        "label"?: string;
        "side"?: boolean;
        "value"?: string;
    }
    interface AppQueryStringToJson {
    }
    interface AppRoot {
    }
    interface AppUrlDecoder {
    }
    interface AppUrlEncoder {
    }
    interface IntrinsicElements {
        "app-base64-decoder": AppBase64Decoder;
        "app-base64-encoder": AppBase64Encoder;
        "app-home": AppHome;
        "app-html-decoder": AppHtmlDecoder;
        "app-html-encoder": AppHtmlEncoder;
        "app-info": AppInfo;
        "app-input": AppInput;
        "app-json-parser": AppJsonParser;
        "app-jwt": AppJwt;
        "app-markdown": AppMarkdown;
        "app-output": AppOutput;
        "app-query-string-to-json": AppQueryStringToJson;
        "app-root": AppRoot;
        "app-url-decoder": AppUrlDecoder;
        "app-url-encoder": AppUrlEncoder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-base64-decoder": LocalJSX.AppBase64Decoder & JSXBase.HTMLAttributes<HTMLAppBase64DecoderElement>;
            "app-base64-encoder": LocalJSX.AppBase64Encoder & JSXBase.HTMLAttributes<HTMLAppBase64EncoderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-html-decoder": LocalJSX.AppHtmlDecoder & JSXBase.HTMLAttributes<HTMLAppHtmlDecoderElement>;
            "app-html-encoder": LocalJSX.AppHtmlEncoder & JSXBase.HTMLAttributes<HTMLAppHtmlEncoderElement>;
            "app-info": LocalJSX.AppInfo & JSXBase.HTMLAttributes<HTMLAppInfoElement>;
            "app-input": LocalJSX.AppInput & JSXBase.HTMLAttributes<HTMLAppInputElement>;
            "app-json-parser": LocalJSX.AppJsonParser & JSXBase.HTMLAttributes<HTMLAppJsonParserElement>;
            "app-jwt": LocalJSX.AppJwt & JSXBase.HTMLAttributes<HTMLAppJwtElement>;
            "app-markdown": LocalJSX.AppMarkdown & JSXBase.HTMLAttributes<HTMLAppMarkdownElement>;
            "app-output": LocalJSX.AppOutput & JSXBase.HTMLAttributes<HTMLAppOutputElement>;
            "app-query-string-to-json": LocalJSX.AppQueryStringToJson & JSXBase.HTMLAttributes<HTMLAppQueryStringToJsonElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-url-decoder": LocalJSX.AppUrlDecoder & JSXBase.HTMLAttributes<HTMLAppUrlDecoderElement>;
            "app-url-encoder": LocalJSX.AppUrlEncoder & JSXBase.HTMLAttributes<HTMLAppUrlEncoderElement>;
        }
    }
}
